"""
app/db/models.py

SQLAlchemy models matching the confirmed final database schema
(SQL generated by the pgAdmin 4 ERD tool).

Relationships: Project -> MergeRequest -> Analysis -> Finding -> GitlabComment
All foreign keys cascade on delete (ON DELETE CASCADE).
"""

from sqlalchemy import (
    Column,
    Integer,
    BigInteger,
    String,
    Text,
    Boolean,
    DateTime,
    ForeignKey,
)
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.db.database import Base


class Project(Base):
    __tablename__ = "project"

    project_id = Column(Integer, primary_key=True)
    project_gitlab_id = Column(BigInteger, nullable=False, unique=True)
    project_name = Column(String(255), nullable=False)
    project_created_at = Column(DateTime, server_default=func.now())

    merge_requests = relationship(
        "MergeRequest", back_populates="project", cascade="all, delete-orphan"
    )


class MergeRequest(Base):
    __tablename__ = "merge_request"

    merge_request_id = Column(Integer, primary_key=True)
    merge_request_project_id = Column(
        Integer, ForeignKey("project.project_id", ondelete="CASCADE")
    )
    merge_request_gitlab_iid = Column(BigInteger, nullable=False)
    merge_request_title = Column(String(255))
    merge_request_status = Column(String(50))
    merge_request_created_at = Column(DateTime, server_default=func.now())

    project = relationship("Project", back_populates="merge_requests")
    analyses = relationship(
        "Analysis", back_populates="merge_request", cascade="all, delete-orphan"
    )


class Analysis(Base):
    __tablename__ = "analysis"

    analysis_id = Column(Integer, primary_key=True)
    analysis_merge_request_id = Column(
        Integer, ForeignKey("merge_request.merge_request_id", ondelete="CASCADE")
    )
    analysis_status = Column(String(50))  # e.g. Pending / Processing / Completed / Failed
    analysis_raw_llm_response = Column(Text)  # raw JSON/text returned by Gemini
    analysis_created_at = Column(DateTime, server_default=func.now())

    merge_request = relationship("MergeRequest", back_populates="analyses")
    findings = relationship(
        "Finding", back_populates="analysis", cascade="all, delete-orphan"
    )


class Finding(Base):
    __tablename__ = "finding"

    finding_id = Column(Integer, primary_key=True)
    finding_analysis_id = Column(
        Integer, ForeignKey("analysis.analysis_id", ondelete="CASCADE")
    )
    finding_file_path = Column(String(255))
    finding_line_number = Column(Integer)
    finding_severity = Column(String(50))
    finding_description = Column(Text)

    analysis = relationship("Analysis", back_populates="findings")
    comments = relationship(
        "GitlabComment", back_populates="finding", cascade="all, delete-orphan"
    )


class GitlabComment(Base):
    __tablename__ = "gitlab_comment"

    gitlab_comment_id = Column(Integer, primary_key=True)
    gitlab_comment_finding_id = Column(
        Integer, ForeignKey("finding.finding_id", ondelete="CASCADE")
    )
    gitlab_comment_gitlab_id = Column(BigInteger, nullable=False)
    gitlab_comment_resolved = Column(Boolean, default=False)
    gitlab_comment_created_at = Column(DateTime, server_default=func.now())

    finding = relationship("Finding", back_populates="comments")